apiVersion: apps/v1
kind: Deployment
metadata:
  name: kalaha
  namespace: kalaha
  labels:
    app: kalaha
spec:
  selector:
    matchLabels:
      app: kalaha
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: kalaha
    spec:
      containers:
        - name: kalaha
          image: {{ .Values.image }}
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 300Mi

      imagePullSecrets:
        - name: regcred
